### ISSUE TITLE
[BUG] : Transfer failed

### ISSUE THREAD

**Issue by KarkatMufiin** [Zagrios/bs-manager#203] opened 2023-04-06 00:09 UTC
I just installed Beat saber manager, and I am trying to transfer the program files to my D drive, and it keeps failing.

**To Reproduce**
1. Go to Settings > Installation folder > Choose folder
2. Click on "Program files" on D drive
3. Wait for it to load

**Expected behaviour**
Files transfer over to D drive.

**Comment by Zagrios** [comment] 2023-04-06 08:07
Hi, thanks for reporting this bug. Could you provide us with the logs of BSManager when you had the bug? 
( Settings -> scroll down -> "Open logs" )

Be careful, your name can be in the logs because of the file paths

**Comment by Zagrios** [comment] 2023-04-06 09:05
Nvm, I managed to reproduce the error. The error is due to shared folders; the problem will be fixed in the next update.

**Closed** 2023-04-10 21:23 UTC
Labels: bug
